services:
  caddy-builder:
    image: caddy:builder-alpine
    volumes:
      - ./caddy_build/:/caddy_build/
    command: xcaddy build --output /caddy_build/caddy --with github.com/caddy-dns/cloudflare

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy_build/caddy:/usr/bin/caddy
    depends_on:
      caddy-builder:
        condition: service_completed_successfully

volumes:
  caddy_data:
  caddy_config:

configs:
  caddyfile:
    content: |
      portainer.tahiro.org {
          reverse_proxy 127.0.0.1:9442
      }
